/********************************************************************
* darkSector_darkAnalysisDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error darkSector_darkAnalysisDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtabledarkSector_darkAnalysisDict();
extern void G__cpp_setup_inheritancedarkSector_darkAnalysisDict();
extern void G__cpp_setup_typetabledarkSector_darkAnalysisDict();
extern void G__cpp_setup_memvardarkSector_darkAnalysisDict();
extern void G__cpp_setup_globaldarkSector_darkAnalysisDict();
extern void G__cpp_setup_memfuncdarkSector_darkAnalysisDict();
extern void G__cpp_setup_funcdarkSector_darkAnalysisDict();
extern void G__set_cpp_environmentdarkSector_darkAnalysisDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "darkSectorEvent.h"
#include "darkSectorMeson.h"
#include "darkSectorTrack.h"
#include "darkSectorUtilities.h"
#include "darkSectorVB.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__darkSector_darkAnalysisDictLN_TClass;
extern G__linked_taginfo G__darkSector_darkAnalysisDictLN_TBuffer;
extern G__linked_taginfo G__darkSector_darkAnalysisDictLN_TMemberInspector;
extern G__linked_taginfo G__darkSector_darkAnalysisDictLN_TObject;
extern G__linked_taginfo G__darkSector_darkAnalysisDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__darkSector_darkAnalysisDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__darkSector_darkAnalysisDictLN_TObjArray;
extern G__linked_taginfo G__darkSector_darkAnalysisDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__darkSector_darkAnalysisDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__darkSector_darkAnalysisDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__darkSector_darkAnalysisDictLN_darkSectorTrack;
extern G__linked_taginfo G__darkSector_darkAnalysisDictLN_darkSectorEvent;
extern G__linked_taginfo G__darkSector_darkAnalysisDictLN_darkSectorMeson;
extern G__linked_taginfo G__darkSector_darkAnalysisDictLN_TFile;
extern G__linked_taginfo G__darkSector_darkAnalysisDictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR;
extern G__linked_taginfo G__darkSector_darkAnalysisDictLN_darkSectorVB;
extern G__linked_taginfo G__darkSector_darkAnalysisDictLN_darkSectorUtilities;
extern G__linked_taginfo G__darkSector_darkAnalysisDictLN_TMatrixTBaselEfloatgR;
extern G__linked_taginfo G__darkSector_darkAnalysisDictLN_TMatrixTBaselEdoublegR;
extern G__linked_taginfo G__darkSector_darkAnalysisDictLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__darkSector_darkAnalysisDictLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__darkSector_darkAnalysisDictLN_TElementActionTlEfloatgR;
extern G__linked_taginfo G__darkSector_darkAnalysisDictLN_TElementPosActionTlEfloatgR;
extern G__linked_taginfo G__darkSector_darkAnalysisDictLN_TMatrixTlEfloatgR;
extern G__linked_taginfo G__darkSector_darkAnalysisDictLN_TMatrixTRow_constlEfloatgR;
extern G__linked_taginfo G__darkSector_darkAnalysisDictLN_TMatrixTRowlEfloatgR;
extern G__linked_taginfo G__darkSector_darkAnalysisDictLN_TMatrixTDiag_constlEfloatgR;
extern G__linked_taginfo G__darkSector_darkAnalysisDictLN_TMatrixTColumn_constlEfloatgR;
extern G__linked_taginfo G__darkSector_darkAnalysisDictLN_TMatrixTFlat_constlEfloatgR;
extern G__linked_taginfo G__darkSector_darkAnalysisDictLN_TMatrixTSub_constlEfloatgR;
extern G__linked_taginfo G__darkSector_darkAnalysisDictLN_TMatrixTSparseRow_constlEfloatgR;
extern G__linked_taginfo G__darkSector_darkAnalysisDictLN_TMatrixTSparseDiag_constlEfloatgR;
extern G__linked_taginfo G__darkSector_darkAnalysisDictLN_TMatrixTColumnlEfloatgR;
extern G__linked_taginfo G__darkSector_darkAnalysisDictLN_TMatrixTDiaglEfloatgR;
extern G__linked_taginfo G__darkSector_darkAnalysisDictLN_TMatrixTFlatlEfloatgR;
extern G__linked_taginfo G__darkSector_darkAnalysisDictLN_TMatrixTSublEfloatgR;
extern G__linked_taginfo G__darkSector_darkAnalysisDictLN_TMatrixTSparseRowlEfloatgR;
extern G__linked_taginfo G__darkSector_darkAnalysisDictLN_TMatrixTSparseDiaglEfloatgR;
extern G__linked_taginfo G__darkSector_darkAnalysisDictLN_TLorentzVector;
extern G__linked_taginfo G__darkSector_darkAnalysisDictLN_vectorlETLorentzVectorcOallocatorlETLorentzVectorgRsPgR;
extern G__linked_taginfo G__darkSector_darkAnalysisDictLN_reverse_iteratorlEvectorlETLorentzVectorcOallocatorlETLorentzVectorgRsPgRcLcLiteratorgR;

/* STUB derived class for protected member access */
